### ISSUE TITLE
Execution issue

### ISSUE THREAD

**Issue by rohitpio** [barrettotte/RPGLE-Twilio#1]
Please can you give me the steps to running on my as400 system.

**Comment by barrettotte** [comment]
My bad, completely forgot to add a setup section to my README.
I added the following section:

## Setup
* Setup Twilio account and a Twilio phone number - https://www.twilio.com/
* Connect to IBMi via SSH - ```ssh USER@YOUR400```
* Clone project - ```git clone https://github.com/barrettotte/RPGLE-Twilio.git```
* Navigate to project - ```cd RPGLE-Twilio```
* Give permissions to build script - ```chmod u+x build.sh```
* Run build script - ```./build.sh```
* The build script will create the following
  * A Library named **TWILIO** to hold all of the Twilio objects
  * A Log table for logging SMS requests - **sms_log**
  * A simplified view over the log table -> **sms_log_v**
  * A stored procedure to call Twilio SMS API -> **send_sms**
  * An RPGLE service program to call Twilio SMS API 
* Example call in [example/src/testtwilio.sqlrpgle](example/src/testtwilio.sqlrpgle)

**Comment by barrettotte** [comment]
closing this issue since i did forget to include the setup instructions.
This is not meant to be a production-ready service program, just something I messed around with in my free time. I'm sure it can be adapted to be something cooler.

Thanks for taking a look at it
